fun main() {
    println("   *    ")
    println("  ***   ")
    println(" *****  ")
    println("******* ")
    println(" *****  ")
    println("  ***   ")
    println("   *    ")
    //or
    println("          *         ")
    println("         ***        ")
    println("        *****       ")
    println("   ***************  ")
    println("    *************   ")
    println("     ***********    ")
    println("      *********     ")
    println("     ***********    ")
    println("    ****** ******   ")
    println("   *****     *****  ")
}